Repository dimonarhipon/one-time-notes, pull requests merged in 2023-08, with the labels that each got.

#23 build: добавляет настройки в vite.config
  .editorconfig
  .github/workflows/build.yaml
  .github/workflows/lint.yaml
  .husky/pre-commit.sh
  .husky/pre-push.sh
  package-lock.json
  package.json
  src/app/providers/RouterProvider/RouterProvider.tsx
  src/pages/AuthorizationPage/AuthorizationPage.module.scss
  src/pages/ModalPage/ModalPage.module.scss
  src/pages/ModalPage/ModalPage.tsx
  src/widgets/Message/Message.tsx
  src/widgets/ModalButton/ModalButton.tsx
  src/widgets/ModalLink/ModalLink.tsx
  src/widgets/ModalTemplate/ModalTemplate.tsx
  src/widgets/ModalTitle/ModalTitle.tsx
  src/widgets/Note/note.module.scss
  src/widgets/NoteButton/NoteButton.module.scss
  src/widgets/NoteCreatedModal/NoteCreatedModal.module.scss
  src/widgets/Preloader/Preloader.module.scss
  src/widgets/Search/Search.module.scss
  src/widgets/SideBar/SideBar.module.scss
  src/widgets/UpdateMenu/updateMenu.module.scss
  src/widgets/UpdateNote/updateNote.module.scss
  tsconfig.node.json
  vite.config.ts
Labels: build

#24 feat: добавление вёрстки и логики
  .editorconfig
  .github/workflows/build.yaml
  .github/workflows/lint.yaml
  .husky/pre-commit.sh
  .husky/pre-push.sh
  README.md
  package-lock.json
  package.json
  src/app/providers/RouterProvider/RouterProvider.tsx
  src/pages/AuthorizationPage/AuthorizationPage.module.scss
  src/pages/ModalPage/ModalPage.module.scss
  src/pages/ModalPage/ModalPage.tsx
  src/shared/Preloader/Preloader.module.scss
  src/shared/Preloader/Preloader.tsx
  src/shared/Preloader/loading.svg
  src/shared/Preloader/loading2.svg
  src/shared/Preloader/point-preloader.svg
  src/shared/api/callApi.ts
  src/shared/api/fetchMethods.ts
  src/shared/api/fetchNotes.ts
  src/shared/lib/NoteClass.ts
  src/shared/lib/NoteType.ts
  src/shared/lib/TModalProps.ts
  src/shared/lib/addNote.ts
  src/shared/lib/removeNote.ts
  src/shared/lib/searchForNotes.ts
  src/shared/lib/sortByCompleted.ts
  src/shared/lib/sortByDate.ts
  src/shared/noteData.json
  src/widgets/AddButton/AddButton.module.scss
  src/widgets/AddButton/AddButton.tsx
  src/widgets/AddButton/addButton.module.scss
  src/widgets/Message/Message.module.scss
  src/widgets/Message/Message.tsx
  src/widgets/ModalButton/ModalButton.module.scss
  src/widgets/ModalButton/ModalButton.tsx
  src/widgets/ModalLink/ModalLink.module.scss
  src/widgets/ModalLink/ModalLink.tsx
  src/widgets/ModalTemplate/ModalTemplate.module.scss
  src/widgets/ModalTemplate/ModalTemplate.tsx
  src/widgets/ModalTitle/ModalTitle.module.scss
  src/widgets/ModalTitle/ModalTitle.tsx
  src/widgets/Note/Note.tsx
  src/widgets/Note/note.module.scss
  src/widgets/NoteButton/NoteButton.module.scss
  src/widgets/NoteButton/NoteButton.tsx
  src/widgets/NoteButton/NoteButtonType.ts
  src/widgets/NoteCreatedModal/NoteCreatedModal.module.scss
  src/widgets/Preloader/Preloader.module.scss
  src/widgets/Preloader/Preloader.tsx
  src/widgets/Search/Search.module.scss
  src/widgets/Search/Search.tsx
  src/widgets/Search/search.module.scss
  src/widgets/SideBar/SideBar.module.scss
  src/widgets/SideBar/SideBar.tsx
  src/widgets/SideBar/sideBar.module.scss
  src/widgets/UpdateMenu/updateMenu.module.scss
  src/widgets/UpdateNote/updateNote.module.scss
  tsconfig.node.json
  vite.config.ts
Labels: feat

#25 docs: update README.md
  README.md
Labels: docs

#26 ci: дорабатывает данные vite.config
  package-lock.json
  package.json
  vite.config.ts
Labels: ci

#27 ci & build: добавляет ci проверки с понижением версии vite
  .eslintrc.cjs
  .github/workflows/build.yaml
  .github/workflows/lint.yaml
  .github/workflows/test.yaml
  README.md
  package-lock.json
  package.json
Labels: build, ci

#30 Get note
  src/app/providers/RouterProvider/RouterProvider.tsx
  src/pages/ErrorPage/ErrorPage.tsx
  src/pages/ErrorPage/index.ts
  src/pages/ModalPage/ModalPage.module.scss
  src/pages/ModalPage/ModalPage.tsx
  src/pages/ModalPage/index.tsx
  src/pages/ModalPage/utils.ts
  src/shared/lib/TGetNote.ts
  src/shared/lib/TModalProps.ts
  src/shared/lib/modalMethods.ts
  src/widgets/Message/Message.module.scss
  src/widgets/Message/Message.tsx
  src/widgets/ModalButton/ModalButton.module.scss
  src/widgets/ModalButton/ModalButton.tsx
  src/widgets/ModalLink/ModalLink.module.scss
  src/widgets/ModalLink/ModalLink.tsx
  src/widgets/ModalTemplate/ModalTemplate.module.scss
  src/widgets/ModalTemplate/ModalTemplate.tsx
  src/widgets/ModalTitle/ModalTitle.module.scss
  src/widgets/ModalTitle/ModalTitle.tsx
  src/widgets/ModalWrapper/ModalWrapper.module.scss
  src/widgets/ModalWrapper/ModalWrapper.tsx
  src/widgets/ModuleError/ErrorContent.module.scss
  src/widgets/ModuleError/ErrorContent.tsx
Labels: fix, feat

#32 style: добавляет адаптив
  index.html
  public/manifest.json
  src/pages/NotesPage/notesPage.module.scss
  src/widgets/Header/Header.module.scss
  src/widgets/SideBar/SideBar.module.scss
Labels: style

#28 Control notes
  package-lock.json
  package.json
  src/app/providers/RouterProvider/RouterProvider.tsx
  src/pages/ModalPage/ModalPage.tsx
  src/pages/ModalPage/utils.ts
  src/shared/api/fetchNotes.ts
  src/shared/api/myFetch.ts
  src/shared/assets/icons/IconLang.tsx
  src/shared/lib/NoteClass.ts
  src/shared/lib/NoteType.ts
  src/shared/lib/addNote.ts
  src/shared/lib/removeNote.ts
  src/shared/lib/searchForNotes.ts
  src/shared/lib/sortByCompleted.ts
  src/shared/lib/sortByDate.ts
  src/shared/styles/_vars.scss
  src/store/hooks.ts
  src/store/notes.slice.ts
  src/store/store.d.ts
  src/store/store.ts
  src/widgets/AddButton/AddButton.module.scss
  src/widgets/AddButton/AddButton.tsx
  src/widgets/ModalLink/ModalLink.module.scss
  src/widgets/NoteItem/NoteItem.module.scss
  src/widgets/NoteItem/NoteItem.tsx
  src/widgets/NoteItem/removeNote.svg
  src/widgets/Search/Search.module.scss
  src/widgets/SideBar/SideBar.module.scss
  src/widgets/SideBar/SideBar.tsx
Labels: feat, refactor

#18 Authbranch обновление авторизации и регистрации
  package-lock.json
  src/app/providers/RouterProvider/RouterProvider.tsx
  src/pages/AuthorizationPage/AuthorizationPage.module.scss
  src/pages/AuthorizationPage/AuthorizationPage.tsx
  src/pages/AuthorizationPage/FormInput.tsx
  src/pages/AuthorizationPage/index.tsx
  src/pages/AuthorizationPage/type.ts
  src/pages/LoginPage/Login.tsx
  src/pages/LoginPage/index.tsx
  src/pages/NotesPage/notesPage.module.scss
  src/pages/RegisterPage/Register.tsx
  src/pages/RegisterPage/index.tsx
  src/shared/Types/AuthTypes.ts
  src/widgets/Form/Form.module.scss
  src/widgets/Form/Form.tsx
  src/widgets/Input/Input.module.scss
  src/widgets/Input/Input.tsx
Labels: feat
